Coral backend: coral::NodeObject Class Reference
coral::NodeObject Class Reference
A class that represents an object of any type.
#include <coral.h>
Public Types
template<typename T, typename ReturnType, typename... Args>
using MethodPtr = ReturnType (T::*)(Args...)
template<typename T, typename ReturnType, typename... Args>
using ConstMethodPtr = ReturnType (T::*)(Args...) const
Public Member Functions
NodeObject ()=default
template<typename T>
NodeObject (const T &data)
Construct a new object from trivially constructible and copyable types.
NodeObject (const std::shared_ptr< entt::meta_any > &data)
Construct NodeObject from a std::shared_ptr<entt::meta_any>.
template<typename T>
NodeObject (std::shared_ptr< T > data)
Construct a new object from a shared pointer to a type.
NodeObject (const std::string &hash_str)
Try to construct a new object from a hash string.
NodeObject (const char *hash_str)
Build a NodeObject from a hash string.
void override_interface (const json &arguments, const json &inputs, const json &outputs)
auto ready () const -> bool
void parse_string (const std::string &value_str)
auto to_string () const -> std::string
auto operator() () -> bool
Run the executor function of the object->
void set_arguments (const std::vector< NodeObjectPtr > &args)
Set the arguments of the node executor.
template<typename T>
auto get_shared () -> std::shared_ptr< T >
Get a shared pointer of the stored object->
template<typename T>
T & get ()
Get a writeable reference to the stored object->
template<typename T>
const T & get () const
Get a const reference to the stored object->
NodeObjectPtr get_output (const unsigned int index)
Return a Pointer to the ith output.
bool is_input_bound (const unsigned int index) const
Returns true if the input at index is bound to a node.
bool is_passthrough_input (const unsigned int index) const
Returns true if the input at index is a pass-through input.
bool is_output_bound (const unsigned int index) const
Returns true if the output at index is bound to a node.
bool is_bindable (const unsigned int index) const
Returns true if the output at index can be rebound.
void bind_output (const unsigned int index, const NodeObjectPtr &value)
Bind the ith output to a new NodeObject.
bool has_unbound_inputs () const
Returns true if any inputs are unbound.
bool has_unbound_outputs () const
Returns true if any outputs are unbound.
NodeObjectPtr get_input (const unsigned int index)
Return a Pointer to the index -th input.
void bind_input (const unsigned int index, const NodeObjectPtr &value)
Bind an input slot to a NodeObject.
template<typename T>
std::shared_ptr< const T > get_shared () const
Get a shared pointer to the underlying object (const).
template<typename T>
NodeObject & operator= (std::shared_ptr< T > data)
Assign from a shared pointer to a registered type.
template<typename T>
NodeObject & operator= (const T &data)
Assign from a value of a registered type.
const json & get_info () const
Return the JSON info record for this node.
std::string hash () const
Get the hash of the stored object->
std::string type_name () const
Return the human-readable type name for this node.
NodeType node_type () const
Return the node type enum.
size_t n_arguments () const
Get the number of arguments that this node has.
size_t n_inputs () const
Get the number of inputs.
size_t n_outputs () const
Get the number of outputs.
void bind_inputs (const std::vector< std::pair< NodeObjectPtr, unsigned int > > &inputs)
Bind all inputs using a list of node/output pairs.
Static Public Member Functions
static auto get_registry () -> json
Return the registry of all types known to this class.
static auto is_network_type (const std::string &hash_str) -> bool
static auto build_network_interface (const std::shared_ptr< entt::meta_any > &value) -> detail::NodeInterface
template<typename T>
static auto register_json_header (const std::string &suffix="") -> detail::NodeObjectInitializer &
Register a new type in the json registry.
template<typename T, typename... Args>
static auto register_json_header (const std::vector< std::string > &arg_names, const std::string &suffix="") -> detail::NodeObjectInitializer &
Register a new type in the json registry, for types that require additional arguments.
template<typename T, typename... Args>
static auto register_type (const std::vector< std::string > &arg_names) -> detail::NodeObjectInitializer &
Register a non-trivially constructible type T with constructor arguments.
template<typename T>
static auto register_elementary_type () -> detail::NodeObjectInitializer &
Register an elementary type.
template<typename T>
static auto register_type () -> detail::NodeObjectInitializer &
Register a trivially constructible type.
template<typename T>
static auto register_abstract_type () -> detail::NodeObjectInitializer &
Register an abstract type.
template<typename B, typename T>
static auto register_derived_type () -> detail::NodeObjectInitializer &
Register a non-trivially constructible type T derived from type B.
template<typename B, typename T, typename... Args>
static auto register_derived_type (const std::vector< std::string > &arg_names) -> detail::NodeObjectInitializer &
template<typename T, typename Arg>
static auto register_type (const std::string &arg_name) -> detail::NodeObjectInitializer &
Same as above, for objects that require a single argument.
template<typename B, typename T, typename Arg>
static auto register_derived_type (const std::string &arg_name) -> detail::NodeObjectInitializer &
Same as above, for objects that require a single argument.
template<typename T, typename ReturnType, typename... Args>
static void register_method (MethodPtr< T, ReturnType, Args... > ptr, std::vector< std::string > arg_names)
Register a non-const method of a class.
template<typename T, typename ReturnType, typename... Args>
static void register_method (ConstMethodPtr< T, ReturnType, Args... > ptr, std::vector< std::string > arg_names)
Register a const method of a class.
template<typename ReturnType, typename... Args>
static void register_function (std::function< ReturnType(Args...)> ptr, std::vector< std::string > arg_names)
Register a free function.
template<typename ReturnType, typename... Args>
static void register_function (ReturnType(*ptr)(Args...), std::vector< std::string > arg_names)
template<typename Lambda>
static void register_function (Lambda func, std::vector< std::string > arg_names)
Private Member Functions
bool is_passthrough_output (const unsigned int index) const
Return true if an output index maps to a pass-through argument.
unsigned int input_index_for_argument (const int argument_index) const
Find the input index that maps to a given argument index.
void initialize_inputs ()
Initialize input index mappings from JSON metadata.
void initialize_outputs ()
Initialize output index mappings from JSON metadata.
void initialize_arguments ()
Initialize argument list and connection types from JSON metadata.
void setup_network_if_needed ()
Configure network-specific interface overrides.
Static Private Member Functions
template<typename T>
static bool is_registered_elementary_type ()
static void set_output_only (detail::NodeObjectInitializer &initializer, unsigned int arg_index)
Mark an argument as output-only in the JSON metadata.
Private Attributes
std::shared_ptr< entt::meta_any > object
The actual object is stored here as a std::shared_ptr<entt::meta_any>.
detail::NodeObjectInitializer initializer
Anything required to build a std::shared_ptr<T> object, and to manipulate it.
std::vector< NodeObjectPtr > arguments
The arguments to pass to the executor.
std::vector< ConnectionType > arguments_types
Arguments to connection type.
std::vector< bool > input_bound
Track whether inputs and outputs have been explicitly bound.
std::vector< bool > output_bound
std::vector< int > input_indices
Input indices mapping to arguments.
std::vector< int > output_indices
Output indices mapping to arguments.
Static Private Attributes
static std::map< std::string, detail::NodeObjectInitializer > initializers
A list of all known types and their initializers.
static std::string network_type_hash
Hash string that identifies the Network node type.
static std::function< detail::NodeInterface(const std::shared_ptr< entt::meta_any > &)> network_interface_builder
Builder for network interfaces from stored values.
Friends
class Network
std::shared_ptr< entt::meta_any > & detail::meta_any_ref (NodeObject &)
const std::shared_ptr< entt::meta_any > & detail::meta_any_ref (const NodeObject &)
Detailed Description
A class that represents an object of any type.
The object itself is stored in a std::shared_ptr<entt::meta_any>. To allow for serialization and to build non trivially constructible classes, the actual type stored in std::shared_ptr<entt::meta_any> is a shared pointer to the object.
The object is built only when calling the operator() function. This allows you to connect arguments to this object, in case the building of the object requires other objects.
coral::NodeObject::register_elementary_type<int>();
coral::NodeObjectPtr value = coral::make_node(3);
if (value->ready())
  (void)(*value)();
int v = value->get<int>();
Definition at line 502 of file coral.h.
Member Typedef Documentation
ConstMethodPtr
template<typename T, typename ReturnType, typename... Args> using coral::NodeObject::ConstMethodPtr = ReturnType (T::*)(Args...) const
Definition at line 796 of file coral.h.
MethodPtr
template<typename T, typename ReturnType, typename... Args> using coral::NodeObject::MethodPtr = ReturnType (T::*)(Args...)
Definition at line 793 of file coral.h.
Constructor & Destructor Documentation
NodeObject() [1/6]
coral::NodeObject::NodeObject () default
References arguments, parse_string(), register_json_header(), register_type(), set_arguments(), and to_string().
Referenced by detail::meta_any_ref, detail::meta_any_ref, NodeObject(), NodeObject(), NodeObject(), NodeObject(), operator=(), and operator=().
NodeObject() [2/6]
template<typename T> coral::NodeObject::NodeObject (const T & data) inline
Construct a new object from trivially constructible and copyable types.
Definition at line 1371 of file coral.h.
References NodeObject().
NodeObject() [3/6]
CORAL_IMPL_INLINE coral::NodeObject::NodeObject (const std::shared_ptr< entt::meta_any > & data)
Construct NodeObject from a std::shared_ptr<entt::meta_any>.
The std::shared_ptr<entt::meta_any> is supposed to contain a shared pointer to a registered type.
Definition at line 15 of file coral_implementation.h.
References hash(), and NodeObject().
NodeObject() [4/6]
template<typename T> coral::NodeObject::NodeObject (std::shared_ptr< T > data) inline
Construct a new object from a shared pointer to a type.
Definition at line 1376 of file coral.h.
References initialize_arguments(), initialize_inputs(), initialize_outputs(), initializer, initializers, and setup_network_if_needed().
NodeObject() [5/6]
CORAL_IMPL_INLINE coral::NodeObject::NodeObject (const std::string & hash_str)
Try to construct a new object from a hash string.
If the hash is not found, we store the actual string.
Definition at line 20 of file coral_implementation.h.
References initialize_arguments(), initialize_inputs(), initialize_outputs(), initializer, initializers, NodeObject(), and setup_network_if_needed().
NodeObject() [6/6]
CORAL_IMPL_INLINE coral::NodeObject::NodeObject (const char * hash_str)
Build a NodeObject from a hash string.
Definition at line 39 of file coral_implementation.h.
References NodeObject().
Member Function Documentation
bind_input()
CORAL_IMPL_INLINE void coral::NodeObject::bind_input (const unsigned int index, const NodeObjectPtr & value)
Bind an input slot to a NodeObject.
node->bind_input(0, other);
Definition at line 496 of file coral_implementation.h.
References arguments, initializer, input_bound, and input_indices.
bind_inputs()
CORAL_IMPL_INLINE void coral::NodeObject::bind_inputs (const std::vector< std::pair< NodeObjectPtr, unsigned int > > & inputs)
Bind all inputs using a list of node/output pairs.
node->bind_inputs({{upstream, 0}});
Definition at line 311 of file coral_implementation.h.
References arguments, initializer, input_bound, and input_indices.
bind_output()
CORAL_IMPL_INLINE void coral::NodeObject::bind_output (const unsigned int index, const NodeObjectPtr & value)
Bind the ith output to a new NodeObject.
node->bind_output(0, output_node);
Definition at line 434 of file coral_implementation.h.
References arguments, is_passthrough_output(), output_bound, and output_indices.
build_network_interface()
CORAL_IMPL_INLINE auto coral::NodeObject::build_network_interface (const std::shared_ptr< entt::meta_any > & value) -> detail::NodeInterface static
Definition at line 65 of file coral_implementation.h.
References network_interface_builder.
Referenced by coral::from_json(), coral::Network::register_node(), and setup_network_if_needed().
get() [1/2]
template<typename T> T & coral::NodeObject::get () inline
Get a writeable reference to the stored object->
Definition at line 1681 of file coral.h.
References get_shared(), and ready().
Referenced by initialize_arguments(), and initialize_outputs().
get() [2/2]
template<typename T> const T & coral::NodeObject::get () const inline
Get a const reference to the stored object->
Definition at line 1692 of file coral.h.
References get_shared(), and ready().
get_info()
CORAL_IMPL_INLINE const json & coral::NodeObject::get_info () const
Return the JSON info record for this node.
Definition at line 521 of file coral_implementation.h.
References initializer, and coral::network.
get_input()
CORAL_IMPL_INLINE NodeObjectPtr coral::NodeObject::get_input (const unsigned int index)
Return a Pointer to the index -th input.
Definition at line 474 of file coral_implementation.h.
References arguments, initializer, and input_indices.
get_output()
CORAL_IMPL_INLINE NodeObjectPtr coral::NodeObject::get_output (const unsigned int index)
Return a Pointer to the ith output.
Definition at line 362 of file coral_implementation.h.
References arguments, and output_indices.
get_registry()
CORAL_IMPL_INLINE auto coral::NodeObject::get_registry () -> json static
Return the registry of all types known to this class.
If you try to instantiate a class that is not in the registry, an exception will be thrown.
Definition at line 44 of file coral_implementation.h.
References initializer, and initializers.
Referenced by dump_registry(), and coral::Network::get_registry().
get_shared() [1/2]
template<typename T> auto coral::NodeObject::get_shared () -> std::shared_ptr<T> inline
Get a shared pointer of the stored object->
Will throw if the object is not ready, or if the stored object is not of the requested type.
Definition at line 1627 of file coral.h.
References hash(), initializer, ready(), and type_name().
Referenced by get(), and get().
get_shared() [2/2]
template<typename T> std::shared_ptr< const T > coral::NodeObject::get_shared () const inline
Get a shared pointer to the underlying object (const).
Definition at line 1703 of file coral.h.
References hash(), initializer, ready(), and type_name().
has_unbound_inputs()
CORAL_IMPL_INLINE bool coral::NodeObject::has_unbound_inputs () const
Returns true if any inputs are unbound.
Definition at line 452 of file coral_implementation.h.
References input_indices, and is_input_bound().
has_unbound_outputs()
CORAL_IMPL_INLINE bool coral::NodeObject::has_unbound_outputs () const
Returns true if any outputs are unbound.
Definition at line 463 of file coral_implementation.h.
References is_output_bound(), and output_indices.
hash()
CORAL_IMPL_INLINE std::string coral::NodeObject::hash () const
Get the hash of the stored object->
Definition at line 550 of file coral_implementation.h.
References initializer.
Referenced by get_shared(), get_shared(), NodeObject(), and operator=().
initialize_arguments()
CORAL_IMPL_INLINE void coral::NodeObject::initialize_arguments () private
Initialize argument list and connection types from JSON metadata.
Definition at line 271 of file coral_implementation.h.
References arguments, arguments_types, get(), initializer, and coral::none.
Referenced by NodeObject(), NodeObject(), override_interface(), and set_arguments().
initialize_inputs()
CORAL_IMPL_INLINE void coral::NodeObject::initialize_inputs () private
Initialize input index mappings from JSON metadata.
Definition at line 221 of file coral_implementation.h.
References initializer, input_bound, and input_indices.
Referenced by NodeObject(), NodeObject(), and override_interface().
initialize_outputs()
CORAL_IMPL_INLINE void coral::NodeObject::initialize_outputs () private
Initialize output index mappings from JSON metadata.
Definition at line 236 of file coral_implementation.h.
References arguments, get(), initializer, output_bound, and output_indices.
Referenced by NodeObject(), NodeObject(), and override_interface().
input_index_for_argument()
CORAL_IMPL_INLINE unsigned int coral::NodeObject::input_index_for_argument (const int argument_index) const private
Find the input index that maps to a given argument index.
Definition at line 630 of file coral_implementation.h.
References input_indices.
Referenced by is_output_bound().
is_bindable()
CORAL_IMPL_INLINE bool coral::NodeObject::is_bindable (const unsigned int index) const
Returns true if the output at index can be rebound.
Definition at line 424 of file coral_implementation.h.
References is_passthrough_output(), and output_indices.
is_input_bound()
CORAL_IMPL_INLINE bool coral::NodeObject::is_input_bound (const unsigned int index) const
Returns true if the input at index is bound to a node.
Definition at line 376 of file coral_implementation.h.
References initializer, input_bound, and input_indices.
Referenced by has_unbound_inputs(), and is_output_bound().
is_network_type()
CORAL_IMPL_INLINE auto coral::NodeObject::is_network_type (const std::string & hash_str) -> bool static
Definition at line 57 of file coral_implementation.h.
References network_type_hash.
Referenced by coral::from_json(), and setup_network_if_needed().
is_output_bound()
CORAL_IMPL_INLINE bool coral::NodeObject::is_output_bound (const unsigned int index) const
Returns true if the output at index is bound to a node.
Definition at line 410 of file coral_implementation.h.
References input_index_for_argument(), is_input_bound(), is_passthrough_output(), output_bound, and output_indices.
Referenced by has_unbound_outputs().
is_passthrough_input()
CORAL_IMPL_INLINE bool coral::NodeObject::is_passthrough_input (const unsigned int index) const
Returns true if the input at index is a pass-through input.
Definition at line 391 of file coral_implementation.h.
References arguments_types, initializer, input_indices, and coral::pass_through.
is_passthrough_output()
CORAL_IMPL_INLINE bool coral::NodeObject::is_passthrough_output (const unsigned int index) const private
Return true if an output index maps to a pass-through argument.
Definition at line 614 of file coral_implementation.h.
References arguments_types, output_indices, and coral::pass_through.
Referenced by bind_output(), is_bindable(), and is_output_bound().
is_registered_elementary_type()
template<typename T> bool coral::NodeObject::is_registered_elementary_type () inline static private
Definition at line 1790 of file coral.h.
References coral::elementary_constructor, and initializers.
Referenced by register_function(), register_method(), and register_method().
n_arguments()
CORAL_IMPL_INLINE size_t coral::NodeObject::n_arguments () const
Get the number of arguments that this node has.
Definition at line 590 of file coral_implementation.h.
References initializer.
n_inputs()
CORAL_IMPL_INLINE size_t coral::NodeObject::n_inputs () const
Get the number of inputs.
Definition at line 598 of file coral_implementation.h.
References initializer.
n_outputs()
CORAL_IMPL_INLINE size_t coral::NodeObject::n_outputs () const
Get the number of outputs.
Definition at line 606 of file coral_implementation.h.
References initializer.
node_type()
CORAL_IMPL_INLINE NodeType coral::NodeObject::node_type () const
Return the node type enum.
Definition at line 580 of file coral_implementation.h.
References initializer.
operator()()
CORAL_IMPL_INLINE auto coral::NodeObject::operator() () -> bool
Run the executor function of the object->
Returns
true If the executor function was run successfully.
false If the executor function failed to run (i.e., if it failed when running or if some of the arguments were not ready.)
Definition at line 142 of file coral_implementation.h.
References arguments, arguments_types, coral::elementary_constructor, initializer, coral::input, coral::none, ready(), and coral::self.
operator=() [1/2]
template<typename T> NodeObject & coral::NodeObject::operator= (const T & data) inline
Assign from a value of a registered type.
Definition at line 1780 of file coral.h.
References NodeObject().
operator=() [2/2]
template<typename T> NodeObject & coral::NodeObject::operator= (std::shared_ptr< T > data) inline
Assign from a shared pointer to a registered type.
Definition at line 1756 of file coral.h.
References hash(), and NodeObject().
override_interface()
CORAL_IMPL_INLINE void coral::NodeObject::override_interface (const json & arguments, const json & inputs, const json & outputs)
Definition at line 76 of file coral_implementation.h.
References arguments, initialize_arguments(), initialize_inputs(), initialize_outputs(), and initializer.
Referenced by setup_network_if_needed().
parse_string()
CORAL_IMPL_INLINE void coral::NodeObject::parse_string (const std::string & value_str)
Definition at line 104 of file coral_implementation.h.
References initializer.
Referenced by NodeObject().
ready()
CORAL_IMPL_INLINE auto coral::NodeObject::ready () const -> bool
Definition at line 96 of file coral_implementation.h.
Referenced by get(), get(), get_shared(), get_shared(), operator()(), register_function(), register_method(), register_method(), setup_network_if_needed(), and to_string().
register_abstract_type()
template<typename T> static auto coral::NodeObject::register_abstract_type () -> detail::NodeObjectInitializer & inline static
Register an abstract type.
This is a type that will never be constructed.
Definition at line 720 of file coral.h.
References coral::abstract, initializer, and register_json_header().
Referenced by register_derived_type(), and register_derived_type().
register_derived_type() [1/3]
template<typename B, typename T> static auto coral::NodeObject::register_derived_type () -> detail::NodeObjectInitializer & inline static
Register a non-trivially constructible type T derived from type B.
Definition at line 740 of file coral.h.
References initializer, register_abstract_type(), and register_type().
Referenced by register_derived_type(), and coral::register_non_dimensional_types().
register_derived_type() [2/3]
template<typename B, typename T, typename Arg> auto coral::NodeObject::register_derived_type (const std::string & arg_name) -> detail::NodeObjectInitializer & inline static
Same as above, for objects that require a single argument.
Definition at line 1596 of file coral.h.
References register_derived_type().
register_derived_type() [3/3]
template<typename B, typename T, typename... Args> auto coral::NodeObject::register_derived_type (const std::vector< std::string > & arg_names) -> detail::NodeObjectInitializer & inline static
Definition at line 1562 of file coral.h.
References initializer, register_abstract_type(), and register_type().
register_elementary_type()
template<typename T> static auto coral::NodeObject::register_elementary_type () -> detail::NodeObjectInitializer & inline static
Register an elementary type.
This is a type that does not require any arguments to be constructed, it is trivially copyable, and its values can be deduced from a string using dealii::Patterns::Tools::parse_string().
Definition at line 622 of file coral.h.
References coral::elementary_constructor, initializer, register_elementary_type(), and register_json_header().
Referenced by register_elementary_type(), and coral::register_non_dimensional_types().
register_function() [1/3]
template<typename Lambda> void coral::NodeObject::register_function (Lambda func, std::vector< std::string > arg_names) inline static
Definition at line 1617 of file coral.h.
References register_function().
register_function() [2/3]
template<typename ReturnType, typename... Args> void coral::NodeObject::register_function (ReturnType(* ptr)(Args...), std::vector< std::string > arg_names) inline static
Definition at line 1606 of file coral.h.
References register_function().
register_function() [3/3]
template<typename ReturnType, typename... Args> static void coral::NodeObject::register_function (std::function< ReturnType(Args...)> ptr, std::vector< std::string > arg_names) inline static
Register a free function.
This node will have as arguments the output of the function, and the arguments of the method.
The function can be void or return a value, and can have any number of arguments.
The first argument of the method is the return type of the class, and the arg_names must reflect this if non-void, i.e., arg_names[0] is the name of the function, while arg_names[1] is the (optional) output node (if non-void) by which we store this function name, while the rest of the arguments are the names of the arguments of the method.
Definition at line 1008 of file coral.h.
References coral::detail::cast_args(), coral::function, initializer, is_registered_elementary_type(), ready(), register_json_header(), set_output_only(), and coral::void_function.
Referenced by coral::register_dimensional_types(), register_function(), and register_function().
register_json_header() [1/2]
template<typename T> auto coral::NodeObject::register_json_header (const std::string & suffix = "") -> detail::NodeObjectInitializer & inline static
Register a new type in the json registry.
This method does not add constructors.
Definition at line 1402 of file coral.h.
References initializer, and initializers.
Referenced by NodeObject(), register_abstract_type(), register_elementary_type(), register_function(), register_json_header(), register_method(), register_method(), coral::Network::register_node(), register_type(), and register_type().
register_json_header() [2/2]
template<typename T, typename... Args> auto coral::NodeObject::register_json_header (const std::vector< std::string > & arg_names, const std::string & suffix = "") -> detail::NodeObjectInitializer & inline static
Register a new type in the json registry, for types that require additional arguments.
This method does not add constructors.
Definition at line 1423 of file coral.h.
References coral::connection_type(), initializer, coral::input, coral::none, coral::output, and register_json_header().
register_method() [1/2]
template<typename T, typename ReturnType, typename... Args> static void coral::NodeObject::register_method (ConstMethodPtr< T, ReturnType, Args... > ptr, std::vector< std::string > arg_names) inline static
Register a const method of a class.
This node will have as arguments the object of the class, possibly the output argument, and the arguments of the method.
The method can be void or return a value, and can have any number of arguments, but it must be a const method of the class.
The first argument of the method is the object of the class, and the arg_names must reflect this, i.e., arg_names[0] is the name by which we store this function name in the json serializer, arg_names[1] must be the (optional) name we give to the output argument, and the rest of the arguments are the names of the arguments of the method.
Definition at line 916 of file coral.h.
References coral::detail::cast_args(), coral::const_method, initializer, is_registered_elementary_type(), ready(), register_json_header(), set_output_only(), and coral::void_const_method.
register_method() [2/2]
template<typename T, typename ReturnType, typename... Args> static void coral::NodeObject::register_method (MethodPtr< T, ReturnType, Args... > ptr, std::vector< std::string > arg_names) inline static
Register a non-const method of a class.
This node will have as arguments the object of the class, possibly the output argument, and the arguments of the method.
The method can be void or return a value, and can have any number of arguments.
The first argument of the method is the object of the class, and the arg_names must reflect this, i.e., arg_names[0] is the name by which we store this function name in the json serializer, arg_names[1] is the name of the class arg_names[2] must be the (optional) name we give to the output argument, and the rest of the arguments are the names of the arguments of the method.
Definition at line 816 of file coral.h.
References coral::detail::cast_args(), initializer, is_registered_elementary_type(), coral::method, ready(), register_json_header(), set_output_only(), and coral::void_method.
Referenced by coral::register_dimensional_types().
register_type() [1/3]
template<typename T> static auto coral::NodeObject::register_type () -> detail::NodeObjectInitializer & inline static
Register a trivially constructible type.
This is a type that does not require any arguments to be constructed, but it is not trivially copyable. This is the case for example of dealii::Triangulation<2>.
Definition at line 696 of file coral.h.
References coral::empty_constructor, initializer, and register_json_header().
Referenced by register_derived_type(), coral::register_non_dimensional_types(), and register_type().
register_type() [2/3]
template<typename T, typename Arg> static auto coral::NodeObject::register_type (const std::string & arg_name) -> detail::NodeObjectInitializer & inline static
Same as above, for objects that require a single argument.
Definition at line 778 of file coral.h.
References register_type().
register_type() [3/3]
template<typename T, typename... Args> auto coral::NodeObject::register_type (const std::vector< std::string > & arg_names) -> detail::NodeObjectInitializer & inline static
Register a non-trivially constructible type T with constructor arguments.
Definition at line 1532 of file coral.h.
References coral::detail::cast_args(), coral::constructor, initializer, and register_json_header().
Referenced by NodeObject(), register_derived_type(), and coral::register_dimensional_types().
set_arguments()
CORAL_IMPL_INLINE void coral::NodeObject::set_arguments (const std::vector< NodeObjectPtr > & args)
Set the arguments of the node executor.
Definition at line 205 of file coral_implementation.h.
References arguments, arguments_types, initialize_arguments(), and initializer.
Referenced by NodeObject().
set_output_only()
CORAL_IMPL_INLINE void coral::NodeObject::set_output_only (detail::NodeObjectInitializer & initializer, unsigned int arg_index) static private
Mark an argument as output-only in the JSON metadata.
Definition at line 641 of file coral_implementation.h.
References initializer, and coral::output.
Referenced by register_function(), register_method(), and register_method().
setup_network_if_needed()
CORAL_IMPL_INLINE void coral::NodeObject::setup_network_if_needed () private
Configure network-specific interface overrides.
Definition at line 289 of file coral_implementation.h.
References build_network_interface(), initializer, is_network_type(), override_interface(), and ready().
Referenced by NodeObject(), and NodeObject().
to_string()
CORAL_IMPL_INLINE auto coral::NodeObject::to_string () const -> std::string
Definition at line 124 of file coral_implementation.h.
References initializer, and ready().
Referenced by NodeObject().
type_name()
CORAL_IMPL_INLINE std::string coral::NodeObject::type_name () const
Return the human-readable type name for this node.
Definition at line 572 of file coral_implementation.h.
References initializer.
Referenced by get_shared(), and get_shared().
Friends And Related Symbol Documentation
detail::meta_any_ref [1/2]
const std::shared_ptr< entt::meta_any > & detail::meta_any_ref (const NodeObject &) friend
References NodeObject().
detail::meta_any_ref [2/2]
std::shared_ptr< entt::meta_any > & detail::meta_any_ref (NodeObject &) friend
References NodeObject().
Network
friend class Network friend
Definition at line 505 of file coral.h.
References Network.
Referenced by Network.
Member Data Documentation
arguments
std::vector<NodeObjectPtr> coral::NodeObject::arguments private
The arguments to pass to the executor.
Definition at line 1277 of file coral.h.
Referenced by bind_input(), bind_inputs(), bind_output(), get_input(), get_output(), initialize_arguments(), initialize_outputs(), NodeObject(), operator()(), override_interface(), and set_arguments().
arguments_types
std::vector<ConnectionType> coral::NodeObject::arguments_types private
Arguments to connection type.
Definition at line 1282 of file coral.h.
Referenced by initialize_arguments(), is_passthrough_input(), is_passthrough_output(), operator()(), and set_arguments().
initializer
detail::NodeObjectInitializer coral::NodeObject::initializer private
Anything required to build a std::shared_ptr<T> object, and to manipulate it.
Definition at line 1272 of file coral.h.
Referenced by bind_input(), bind_inputs(), get_info(), get_input(), get_registry(), get_shared(), get_shared(), hash(), initialize_arguments(), initialize_inputs(), initialize_outputs(), is_input_bound(), is_passthrough_input(), n_arguments(), n_inputs(), n_outputs(), node_type(), NodeObject(), NodeObject(), operator()(), override_interface(), parse_string(), register_abstract_type(), register_derived_type(), register_derived_type(), register_elementary_type(), register_function(), register_json_header(), register_json_header(), register_method(), register_method(), register_type(), register_type(), set_arguments(), set_output_only(), setup_network_if_needed(), to_string(), and type_name().
initializers
std::map<std::string, detail::NodeObjectInitializer> coral::NodeObject::initializers inline static private
A list of all known types and their initializers.
Definition at line 1296 of file coral.h.
Referenced by get_registry(), is_registered_elementary_type(), NodeObject(), NodeObject(), and register_json_header().
input_bound
std::vector<bool> coral::NodeObject::input_bound private
Track whether inputs and outputs have been explicitly bound.
Definition at line 1287 of file coral.h.
Referenced by bind_input(), bind_inputs(), initialize_inputs(), and is_input_bound().
input_indices
std::vector<int> coral::NodeObject::input_indices private
Input indices mapping to arguments.
Definition at line 1324 of file coral.h.
Referenced by bind_input(), bind_inputs(), get_input(), has_unbound_inputs(), initialize_inputs(), input_index_for_argument(), is_input_bound(), and is_passthrough_input().
network_interface_builder
std::function<detail::NodeInterface(const std::shared_ptr<entt::meta_any> &)> coral::NodeObject::network_interface_builder inline static private
Builder for network interfaces from stored values.
Definition at line 1308 of file coral.h.
Referenced by build_network_interface(), and coral::Network::register_node().
network_type_hash
std::string coral::NodeObject::network_type_hash inline static private
Hash string that identifies the Network node type.
Definition at line 1301 of file coral.h.
Referenced by is_network_type(), and coral::Network::register_node().
object
std::shared_ptr<entt::meta_any> coral::NodeObject::object private
The actual object is stored here as a std::shared_ptr<entt::meta_any>.
Definition at line 1266 of file coral.h.
Referenced by coral::detail::meta_any_ref(), and coral::detail::meta_any_ref().
output_bound
std::vector<bool> coral::NodeObject::output_bound private
Definition at line 1288 of file coral.h.
Referenced by bind_output(), initialize_outputs(), and is_output_bound().
output_indices
std::vector<int> coral::NodeObject::output_indices private
Output indices mapping to arguments.
If the content is -1, then we return the object itself.
Definition at line 1330 of file coral.h.
Referenced by bind_output(), get_output(), has_unbound_outputs(), initialize_outputs(), is_bindable(), is_output_bound(), and is_passthrough_output().
The documentation for this class was generated from the following files:
coral.h
coral_implementation.h