Coral backend: coral::Network Class Reference
coral::Network Class Reference
Graph of nodes and connections with Taskflow execution.
#include <coral_network.h>
Classes
struct DanglingPort
Public Types
using Interface = detail::NodeInterface
Public Member Functions
Network ()
Network (const Network &other)
Network & operator= (const Network &other)
Network (Network &&) noexcept
Network & operator= (Network &&) noexcept
void add_node (unsigned int id, const NodeObjectPtr &node, const std::string &node_name="")
unsigned int add_node (const NodeObjectPtr &node, const std::string &node_name="")
void set_node_name (unsigned int id, const std::string &name)
std::string get_node_name (unsigned int id) const
const std::map< unsigned int, std::string > & get_nodes_name () const
void add_connection (unsigned int id, const Connection &conn)
void add_connection (unsigned int id, unsigned int source_id, unsigned int target_id, unsigned int source_output, unsigned int target_input)
unsigned int add_connection (unsigned int source_id, unsigned int target_id, unsigned int source_output, unsigned int target_input)
unsigned int add_connection (const Connection &conn)
void remove_nodes_and_connections (const std::vector< unsigned int > &node_ids, const std::vector< unsigned int > &connection_ids)
unsigned int n_connections () const
unsigned int n_nodes () const
nlohmann::json get_registry () const
void from_json (const nlohmann::json &json_data)
auto to_json () const -> nlohmann::json
void run ()
void clear_network ()
auto get_node (unsigned int id) const -> NodeObjectPtr
auto size () const -> size_t
auto get_taskflow () -> tf::Taskflow &
void output_dot (const std::filesystem::path &filepath) const
auto get_connected_nodes (unsigned int nodeId) const -> std::vector< unsigned int >
auto get_node_connections (unsigned int nodeId) const -> std::vector< Connection >
auto get_inputs () const -> std::vector< std::pair< unsigned int, unsigned int > >
auto n_inputs () const -> size_t
auto get_outputs () const -> std::vector< std::pair< unsigned int, unsigned int > >
auto n_outputs () const -> size_t
NodeObjectPtr get_input (const unsigned int index)
NodeObjectPtr get_output (const unsigned int index)
auto build_interface () const -> Interface
auto get_task (unsigned int id) const -> tf::Task
auto is_connected (unsigned int inId, unsigned int outId) const -> bool
Static Public Member Functions
static void register_node ()
static void set_touch_file_base_path (const std::filesystem::path &path)
static void set_threads_number (size_t nth)
Private Member Functions
void rebuild_taskflow ()
auto get_arguments () const -> std::vector< DanglingPort >
auto connections_to_json () const -> nlohmann::json
auto nodes_to_json () const -> nlohmann::json
void refresh_dynamic_inputs (unsigned int target_id)
void execute_node_task (unsigned int node_id, const NodeObjectPtr &node, const std::string &node_name)
Private Attributes
std::map< unsigned int, NodeObjectPtr > nodes
std::map< unsigned int, std::string > nodes_name
std::map< unsigned int, tf::Task > node_tasks
std::map< unsigned int, Connection > connections
tf::Taskflow taskflow
std::string name
Static Private Attributes
static size_t n_threads = std::thread::hardware_concurrency()
static std::filesystem::path touch_file_base_path {"./"}
Detailed Description
Graph of nodes and connections with Taskflow execution.
Definition at line 46 of file coral_network.h.
Member Typedef Documentation
Interface
using coral::Network::Interface = detail::NodeInterface
Definition at line 49 of file coral_network.h.
Constructor & Destructor Documentation
Network() [1/3]
CORAL_IMPL_INLINE coral::Network::Network () default
References Network().
Referenced by Network(), Network(), Network(), operator=(), operator=(), refresh_dynamic_inputs(), and register_node().
Network() [2/3]
CORAL_IMPL_INLINE coral::Network::Network (const Network & other)
Definition at line 103 of file coral_network_implementation.h.
References connections, Network(), nodes, nodes_name, and rebuild_taskflow().
Network() [3/3]
CORAL_IMPL_INLINE coral::Network::Network (Network &&) default noexcept
References Network().
Member Function Documentation
add_connection() [1/4]
CORAL_IMPL_INLINE unsigned int coral::Network::add_connection (const Connection & conn)
Definition at line 428 of file coral_network_implementation.h.
References add_connection(), and connections.
add_connection() [2/4]
CORAL_IMPL_INLINE void coral::Network::add_connection (unsigned int id, const Connection & conn)
Definition at line 325 of file coral_network_implementation.h.
References connections, get_node_name(), node_tasks, nodes, set_node_name(), size(), coral::Connection::source_id, coral::Connection::source_output, coral::Connection::target_id, and coral::Connection::target_input.
Referenced by add_connection(), add_connection(), add_connection(), from_json(), and operator=().
add_connection() [3/4]
CORAL_IMPL_INLINE void coral::Network::add_connection (unsigned int id, unsigned int source_id, unsigned int target_id, unsigned int source_output, unsigned int target_input)
Definition at line 403 of file coral_network_implementation.h.
References add_connection().
add_connection() [4/4]
CORAL_IMPL_INLINE unsigned int coral::Network::add_connection (unsigned int source_id, unsigned int target_id, unsigned int source_output, unsigned int target_input)
Definition at line 416 of file coral_network_implementation.h.
References add_connection().
add_node() [1/2]
CORAL_IMPL_INLINE unsigned int coral::Network::add_node (const NodeObjectPtr & node, const std::string & node_name = "")
Definition at line 284 of file coral_network_implementation.h.
References add_node(), and nodes.
add_node() [2/2]
CORAL_IMPL_INLINE void coral::Network::add_node (unsigned int id, const NodeObjectPtr & node, const std::string & node_name = "")
Definition at line 256 of file coral_network_implementation.h.
References execute_node_task(), name, node_tasks, nodes, nodes_name, and taskflow.
Referenced by add_node(), from_json(), and operator=().
build_interface()
CORAL_IMPL_INLINE auto coral::Network::build_interface () const -> Interface
Definition at line 806 of file coral_network_implementation.h.
References get_arguments(), coral::input, nodes, coral::none, and coral::output.
Referenced by operator=().
clear_network()
CORAL_IMPL_INLINE void coral::Network::clear_network ()
Definition at line 606 of file coral_network_implementation.h.
References connections, node_tasks, nodes, and taskflow.
Referenced by from_json(), and operator=().
connections_to_json()
CORAL_IMPL_INLINE auto coral::Network::connections_to_json () const -> nlohmann::json private
Definition at line 953 of file coral_network_implementation.h.
References connections.
Referenced by to_json().
execute_node_task()
CORAL_IMPL_INLINE void coral::Network::execute_node_task (unsigned int node_id, const NodeObjectPtr & node, const std::string & node_name) private
Definition at line 189 of file coral_network_implementation.h.
References coral::Failed, refresh_dynamic_inputs(), coral::Running, coral::Succeeded, coral::touch_file(), and touch_file_base_path.
Referenced by add_node(), and rebuild_taskflow().
from_json()
CORAL_IMPL_INLINE void coral::Network::from_json (const nlohmann::json & json_data)
Definition at line 508 of file coral_network_implementation.h.
References add_connection(), add_node(), clear_network(), coral::Connection::from_json(), and size().
Referenced by coral::from_json(), and operator=().
get_arguments()
CORAL_IMPL_INLINE auto coral::Network::get_arguments () const -> std::vector<DanglingPort> private
Definition at line 864 of file coral_network_implementation.h.
References connections, coral::input, nodes, coral::none, coral::output, and coral::pass_through.
Referenced by build_interface().
get_connected_nodes()
CORAL_IMPL_INLINE auto coral::Network::get_connected_nodes (unsigned int nodeId) const -> std::vector<unsigned int>
Definition at line 656 of file coral_network_implementation.h.
References connections.
Referenced by operator=().
get_input()
CORAL_IMPL_INLINE NodeObjectPtr coral::Network::get_input (const unsigned int index)
Definition at line 774 of file coral_network_implementation.h.
References get_inputs(), and nodes.
Referenced by operator=().
get_inputs()
CORAL_IMPL_INLINE auto coral::Network::get_inputs () const -> std::vector<std::pair<unsigned int, unsigned int>>
Definition at line 694 of file coral_network_implementation.h.
References connections, n_inputs(), and nodes.
Referenced by get_input(), n_inputs(), and operator=().
get_node()
CORAL_IMPL_INLINE auto coral::Network::get_node (unsigned int id) const -> NodeObjectPtr
Definition at line 621 of file coral_network_implementation.h.
References nodes.
Referenced by operator=().
get_node_connections()
CORAL_IMPL_INLINE auto coral::Network::get_node_connections (unsigned int nodeId) const -> std::vector<Connection>
Definition at line 675 of file coral_network_implementation.h.
References connections.
Referenced by operator=().
get_node_name()
CORAL_IMPL_INLINE std::string coral::Network::get_node_name (unsigned int id) const
Definition at line 308 of file coral_network_implementation.h.
References nodes_name.
Referenced by add_connection(), nodes_to_json(), operator=(), and rebuild_taskflow().
get_nodes_name()
CORAL_IMPL_INLINE const std::map< unsigned int, std::string > & coral::Network::get_nodes_name () const
Definition at line 317 of file coral_network_implementation.h.
References nodes_name.
Referenced by operator=().
get_output()
CORAL_IMPL_INLINE NodeObjectPtr coral::Network::get_output (const unsigned int index)
Definition at line 790 of file coral_network_implementation.h.
References get_outputs(), and nodes.
Referenced by operator=().
get_outputs()
CORAL_IMPL_INLINE auto coral::Network::get_outputs () const -> std::vector<std::pair<unsigned int, unsigned int>>
Definition at line 734 of file coral_network_implementation.h.
References connections, n_outputs(), and nodes.
Referenced by get_output(), n_outputs(), and operator=().
get_registry()
CORAL_IMPL_INLINE json coral::Network::get_registry () const
Definition at line 476 of file coral_network_implementation.h.
References coral::NodeObject::get_registry(), and nodes.
Referenced by operator=().
get_task()
CORAL_IMPL_INLINE auto coral::Network::get_task (unsigned int id) const -> tf::Task
Definition at line 850 of file coral_network_implementation.h.
References node_tasks.
Referenced by operator=().
get_taskflow()
CORAL_IMPL_INLINE auto coral::Network::get_taskflow () -> tf::Taskflow &
Definition at line 638 of file coral_network_implementation.h.
References taskflow.
Referenced by operator=().
is_connected()
CORAL_IMPL_INLINE auto coral::Network::is_connected (unsigned int inId, unsigned int outId) const -> bool
Definition at line 995 of file coral_network_implementation.h.
References connections.
Referenced by operator=().
n_connections()
CORAL_IMPL_INLINE unsigned int coral::Network::n_connections () const
Definition at line 460 of file coral_network_implementation.h.
References connections.
Referenced by operator=().
n_inputs()
CORAL_IMPL_INLINE auto coral::Network::n_inputs () const -> size_t
Definition at line 726 of file coral_network_implementation.h.
References get_inputs().
Referenced by get_inputs(), and operator=().
n_nodes()
CORAL_IMPL_INLINE unsigned int coral::Network::n_nodes () const
Definition at line 468 of file coral_network_implementation.h.
References nodes.
Referenced by operator=().
n_outputs()
CORAL_IMPL_INLINE auto coral::Network::n_outputs () const -> size_t
Definition at line 766 of file coral_network_implementation.h.
References get_outputs().
Referenced by get_outputs(), and operator=().
nodes_to_json()
CORAL_IMPL_INLINE auto coral::Network::nodes_to_json () const -> nlohmann::json private
Definition at line 966 of file coral_network_implementation.h.
References coral::elementary_constructor, get_node_name(), name, and nodes.
Referenced by to_json().
operator=() [1/2]
CORAL_IMPL_INLINE Network & coral::Network::operator= (const Network & other)
Definition at line 114 of file coral_network_implementation.h.
References connections, Network(), nodes, nodes_name, and rebuild_taskflow().
operator=() [2/2]
CORAL_IMPL_INLINE Network & coral::Network::operator= (Network &&) default noexcept
References add_connection(), add_node(), build_interface(), coral::build_network_interface(), clear_network(), from_json(), get_connected_nodes(), get_input(), get_inputs(), get_node(), get_node_connections(), get_node_name(), get_nodes_name(), get_output(), get_outputs(), get_registry(), get_task(), get_taskflow(), is_connected(), n_connections(), n_inputs(), n_nodes(), n_outputs(), name, Network(), output_dot(), register_node(), remove_nodes_and_connections(), run(), set_node_name(), set_threads_number(), set_touch_file_base_path(), size(), and to_json().
output_dot()
CORAL_IMPL_INLINE void coral::Network::output_dot (const std::filesystem::path & filepath) const
Definition at line 646 of file coral_network_implementation.h.
References taskflow.
Referenced by operator=().
rebuild_taskflow()
CORAL_IMPL_INLINE void coral::Network::rebuild_taskflow () private
Definition at line 222 of file coral_network_implementation.h.
References connections, execute_node_task(), get_node_name(), name, node_tasks, nodes, and taskflow.
Referenced by Network(), operator=(), and remove_nodes_and_connections().
refresh_dynamic_inputs()
CORAL_IMPL_INLINE void coral::Network::refresh_dynamic_inputs (unsigned int target_id) private
Definition at line 132 of file coral_network_implementation.h.
References connections, Network(), nodes, and refresh_dynamic_inputs().
Referenced by execute_node_task(), and refresh_dynamic_inputs().
register_node()
CORAL_IMPL_INLINE void coral::Network::register_node () static
Definition at line 1067 of file coral_network_implementation.h.
References coral::build_network_interface(), coral::NodeObject::build_network_interface(), coral::input, coral::detail::meta_any_ref(), Network(), coral::network, coral::NodeObject::network_interface_builder, coral::NodeObject::network_type_hash, coral::none, coral::pass_through, and coral::NodeObject::register_json_header().
Referenced by operator=(), and coral::register_non_dimensional_types().
remove_nodes_and_connections()
CORAL_IMPL_INLINE void coral::Network::remove_nodes_and_connections (const std::vector< unsigned int > & node_ids, const std::vector< unsigned int > & connection_ids)
Definition at line 438 of file coral_network_implementation.h.
References connections, nodes, nodes_name, and rebuild_taskflow().
Referenced by operator=().
run()
CORAL_IMPL_INLINE void coral::Network::run ()
Definition at line 584 of file coral_network_implementation.h.
References connections, n_threads, nodes, and taskflow.
Referenced by operator=().
set_node_name()
CORAL_IMPL_INLINE void coral::Network::set_node_name (unsigned int id, const std::string & name)
Definition at line 294 of file coral_network_implementation.h.
References name, node_tasks, nodes, and nodes_name.
Referenced by add_connection(), and operator=().
set_threads_number()
CORAL_IMPL_INLINE void coral::Network::set_threads_number (size_t nth) static
Definition at line 183 of file coral_network_implementation.h.
References n_threads.
Referenced by main(), and operator=().
set_touch_file_base_path()
CORAL_IMPL_INLINE void coral::Network::set_touch_file_base_path (const std::filesystem::path & path) static
Definition at line 147 of file coral_network_implementation.h.
References touch_file_base_path.
Referenced by main(), and operator=().
size()
CORAL_IMPL_INLINE auto coral::Network::size () const -> size_t
Definition at line 630 of file coral_network_implementation.h.
References nodes.
Referenced by add_connection(), from_json(), and operator=().
to_json()
CORAL_IMPL_INLINE auto coral::Network::to_json () const -> nlohmann::json nodiscard
Definition at line 1012 of file coral_network_implementation.h.
References connections_to_json(), and nodes_to_json().
Referenced by operator=(), and coral::to_json().
Member Data Documentation
connections
std::map<unsigned int, Connection> coral::Network::connections private
Definition at line 64 of file coral_network.h.
Referenced by add_connection(), add_connection(), clear_network(), connections_to_json(), get_arguments(), get_connected_nodes(), get_inputs(), get_node_connections(), get_outputs(), is_connected(), n_connections(), Network(), operator=(), rebuild_taskflow(), refresh_dynamic_inputs(), remove_nodes_and_connections(), and run().
n_threads
CORAL_IMPL_INLINE size_t coral::Network::n_threads = std::thread::hardware_concurrency() static private
Definition at line 67 of file coral_network.h.
Referenced by run(), and set_threads_number().
name
std::string coral::Network::name private
Definition at line 66 of file coral_network.h.
Referenced by add_node(), nodes_to_json(), operator=(), rebuild_taskflow(), and set_node_name().
node_tasks
std::map<unsigned int, tf::Task> coral::Network::node_tasks private
Definition at line 63 of file coral_network.h.
Referenced by add_connection(), add_node(), clear_network(), get_task(), rebuild_taskflow(), and set_node_name().
nodes
std::map<unsigned int, NodeObjectPtr> coral::Network::nodes private
Definition at line 61 of file coral_network.h.
Referenced by add_connection(), add_node(), add_node(), build_interface(), clear_network(), get_arguments(), get_input(), get_inputs(), get_node(), get_output(), get_outputs(), get_registry(), n_nodes(), Network(), nodes_to_json(), operator=(), rebuild_taskflow(), refresh_dynamic_inputs(), remove_nodes_and_connections(), run(), set_node_name(), and size().
nodes_name
std::map<unsigned int, std::string> coral::Network::nodes_name private
Definition at line 62 of file coral_network.h.
Referenced by add_node(), get_node_name(), get_nodes_name(), Network(), operator=(), remove_nodes_and_connections(), and set_node_name().
taskflow
tf::Taskflow coral::Network::taskflow private
Definition at line 65 of file coral_network.h.
Referenced by add_node(), clear_network(), get_taskflow(), output_dot(), rebuild_taskflow(), and run().
touch_file_base_path
CORAL_IMPL_INLINE std::filesystem::path coral::Network::touch_file_base_path {"./"} static private
Definition at line 68 of file coral_network.h.
Referenced by execute_node_task(), and set_touch_file_base_path().
The documentation for this class was generated from the following files:
coral_network.h
coral_network_implementation.h