Coral backend: coral::detail Namespace Reference
coral::detail Namespace Reference
Functions
template<typename... Args>
std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > cast_args (const std::vector< NodeObjectPtr > &args)
std::shared_ptr< entt::meta_any > & meta_any_ref (NodeObject &node)
const std::shared_ptr< entt::meta_any > & meta_any_ref (const NodeObject &node)
auto type_aliases () -> std::unordered_map< std::size_t, std::string > &
auto type_aliases_mutex () -> std::mutex &
const char * store_identifier (const std::string &id)
auto type_identifier (const entt::meta_type &type, const std::string &suffix="") -> std::string
template<typename Base, typename Derived>
std::shared_ptr< Base > shared_ptr_to_base (const std::shared_ptr< Derived > &ptr)
CORAL_IMPL_INLINE auto validate_and_reorder_network_interface (const json &args, const json &inputs, const json &outputs, const detail::NodeInterface &expected_iface) -> std::tuple< json, json, json >
Function Documentation
cast_args()
template<typename... Args> std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > coral::detail::cast_args (const std::vector< NodeObjectPtr > & args) inline
Referenced by coral::NodeObject::register_function(), coral::NodeObject::register_method(), coral::NodeObject::register_method(), and coral::NodeObject::register_type().
meta_any_ref() [1/2]
CORAL_IMPL_INLINE const std::shared_ptr< entt::meta_any > & coral::detail::meta_any_ref (const NodeObject & node)
Definition at line 920 of file coral_implementation.h.
References coral::NodeObject::object.
meta_any_ref() [2/2]
CORAL_IMPL_INLINE std::shared_ptr< entt::meta_any > & coral::detail::meta_any_ref (NodeObject & node)
Definition at line 912 of file coral_implementation.h.
References coral::NodeObject::object.
Referenced by coral::from_json(), and coral::Network::register_node().
shared_ptr_to_base()
template<typename Base, typename Derived> std::shared_ptr< Base > coral::detail::shared_ptr_to_base (const std::shared_ptr< Derived > & ptr)
Definition at line 107 of file coral.h.
store_identifier()
const char * coral::detail::store_identifier (const std::string & id) inline
Definition at line 79 of file coral.h.
type_aliases()
auto coral::detail::type_aliases () -> std::unordered_map<std::size_t, std::string> & inline
Definition at line 63 of file coral.h.
type_aliases_mutex()
auto coral::detail::type_aliases_mutex () -> std::mutex & inline
Definition at line 70 of file coral.h.
type_identifier()
auto coral::detail::type_identifier (const entt::meta_type & type, const std::string & suffix = "") -> std::string inline
Definition at line 90 of file coral.h.
validate_and_reorder_network_interface()
CORAL_IMPL_INLINE auto coral::detail::validate_and_reorder_network_interface (const json & args, const json & inputs, const json & outputs, const detail::NodeInterface & expected_iface) -> std::tuple<json, json, json>
Definition at line 684 of file coral_implementation.h.
Referenced by coral::from_json().