Coral backend: coral Namespace Reference
coral Namespace Reference
Namespaces
namespace detail
Classes
class Connection
struct is_callable
struct is_callable< Arg, std::void_t< decltype(std::function{std::declval< Arg >()})> >
class Network
class NodeObject
A class that represents an object of any type.
struct NodeObjectInitializer
Store all std::functions that need to be used to build a NodeObject, and the corresponding json serialization.
Typedefs
using NodeObjectPtr = std::shared_ptr<NodeObject>
Enumerations
enum class ConnectionType : unsigned int {
none = 0x000 , input = 0x001 , output = 0x002 , pass_through = 0x003 ,
self = 0x006
}
The different types of connections that can be made between nodes.
enum class NodeType : unsigned int {
none , abstract , elementary_constructor , empty_constructor ,
constructor , void_method , void_const_method , method ,
const_method , void_function , function
}
The different types of nodes.
Functions
template<typename... Args>
std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > cast_args (const std::vector< std::shared_ptr< NodeObject > > &args)
Cast a vector of NodeObject arguments to a tuple of shared pointers.
template<typename T>
auto hash (const std::string &suffix="") -> std::string
Provide a string that can be used as a hash for a type.
auto hash (const entt::meta_any &obj, const std::string &suffix="") -> std::string
template<typename T>
void set_type_alias (const std::string &alias)
Allow callers to override the canonical name used for a given type.
auto hash (const std::shared_ptr< entt::meta_any > &obj, const std::string &suffix="") -> std::string
template<typename T>
auto hash (const T &&, const std::string &suffix="") -> std::string
Provide a string that can be used as a hash for a type.
template<typename... Args>
auto make_node (Args &&...args) -> NodeObjectPtr
Construct a pointer to a NodeObject from the arguments of the constructor.
template<typename T>
auto make_node () -> NodeObjectPtr
Construct a pointer to a NodeObject from a type T.
template<typename Arg>
auto make_method_node (const std::string &method_name, Arg &&) -> NodeObjectPtr
Construct a pointer to a NodeObject for a named method.
template<typename T>
auto connection_type () -> ConnectionType
Distinguish input arguments of a function from being input or input/output arguments.
void to_json (json &j, const NodeObjectPtr &obj)
json serialization of a Nodeobject->
void from_json (const json &j, NodeObjectPtr &obj)
json deserialization of a Nodeobject->
template<typename... Args, std::size_t... Is>
std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > cast_args_impl (const std::vector< std::shared_ptr< NodeObject > > &args, std::index_sequence< Is... >)
Implementation of cast_args function.
void connect (NodeObjectPtr &node, const std::vector< std::pair< NodeObjectPtr, unsigned int > > &inputs={})
Connect the inputs of a node.
void from_json (const json &j, Network &net)
void to_json (json &j, const Network &net)
void to_json (json &j, const Connection &conn)
void from_json (const json &j, Connection &conn)
void register_non_dimensional_types ()
template<int dim, int spacedim>
void register_dimensional_types ()
void register_all_types ()
Typedef Documentation
NodeObjectPtr
using coral::NodeObjectPtr = std::shared_ptr<NodeObject>
Definition at line 41 of file coral.h.
Enumeration Type Documentation
ConnectionType
enum class coral::ConnectionType : unsigned int strong
The different types of connections that can be made between nodes.
Enumerator
none
Invalid connection type.
input
Input only.
output
Output only.
pass_through
Input and output.
self
Special connection to indicate that this input/output is the node itself.
Definition at line 218 of file coral.h.
NodeType
enum class coral::NodeType : unsigned int strong
The different types of nodes.
Enumerator
none
The node has not been initialized with an object.
abstract
This is an abstract type. It will never be instantiated.
elementary_constructor
Trivially copyable and constructible types.
empty_constructor
Non trivially copyable, but trivially constructible types.
constructor
Non trivially copyable, and non trivially constructible types.
void_method
void member function
void_const_method
void const member function
method
non void member function
const_method
non void const member function
void_function
void function
function
non void function
Definition at line 235 of file coral.h.
Function Documentation
cast_args()
template<typename... Args> std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > coral::cast_args (const std::vector< std::shared_ptr< NodeObject > > & args) inline
Cast a vector of NodeObject arguments to a tuple of shared pointers.
Definition at line 1777 of file coral.h.
References cast_args_impl().
Referenced by coral::NodeObject::register_function(), coral::NodeObject::register_method(), coral::NodeObject::register_method(), and coral::NodeObject::register_type().
cast_args_impl()
template<typename... Args, std::size_t... Is> std::tuple< std::shared_ptr< std::remove_const_t< std::remove_reference_t< Args > > >... > coral::cast_args_impl (const std::vector< std::shared_ptr< NodeObject > > & args, std::index_sequence< Is... >) inline
Implementation of cast_args function.
Definition at line 1755 of file coral.h.
Referenced by cast_args().
connect()
void coral::connect (NodeObjectPtr & node, const std::vector< std::pair< NodeObjectPtr, unsigned int > > & inputs = {}) inline
Connect the inputs of a node.
This function sets the inputs of node to the output connectors of nodes in inputs, in particular, it sets the input of the node to inputs[i].first->outputs[inputs[i].second].
Parameters
node The node to connect
inputs The pair input/output connector of the node
Definition at line 1793 of file coral.h.
connection_type()
template<typename T> auto coral::connection_type () -> ConnectionType inline
Distinguish input arguments of a function from being input or input/output arguments.
Definition at line 267 of file coral.h.
References input, and pass_through.
Referenced by coral::NodeObject::register_json_header().
from_json() [1/3]
void coral::from_json (const json & j, Connection & conn) inline
Definition at line 540 of file coral_network.h.
References coral::Connection::from_json().
from_json() [2/3]
void coral::from_json (const json & j, Network & net) inline
Definition at line 522 of file coral_network.h.
References coral::Network::from_json().
from_json() [3/3]
void coral::from_json (const json & j, NodeObjectPtr & obj) inline
json deserialization of a Nodeobject->
Definition at line 1705 of file coral.h.
References make_node().
hash() [1/4]
auto coral::hash (const entt::meta_any & obj, const std::string & suffix = "") -> std::string inline
Definition at line 128 of file coral.h.
References coral::detail::type_identifier().
hash() [2/4]
auto coral::hash (const std::shared_ptr< entt::meta_any > & obj, const std::string & suffix = "") -> std::string inline
Definition at line 145 of file coral.h.
References hash().
hash() [3/4]
template<typename T> auto coral::hash (const std::string & suffix = "") -> std::string inline
Provide a string that can be used as a hash for a type.
Definition at line 91 of file coral.h.
References coral::detail::store_identifier(), coral::detail::type_aliases(), and coral::detail::type_identifier().
Referenced by coral::NodeObject::get_shared(), coral::NodeObject::get_shared(), hash(), hash(), coral::NodeObject::hash(), coral::NodeObject::is_registered_elementary_type(), make_method_node(), make_node(), coral::NodeObject::NodeObject(), coral::NodeObject::operator=(), and coral::NodeObject::register_json_header().
hash() [4/4]
template<typename T> auto coral::hash (const T && , const std::string & suffix = "") -> std::string inline
Provide a string that can be used as a hash for a type.
Definition at line 156 of file coral.h.
References hash().
make_method_node()
template<typename Arg> auto coral::make_method_node (const std::string & method_name, Arg &&) -> NodeObjectPtr inline
Construct a pointer to a NodeObject for a named method.
Definition at line 199 of file coral.h.
References hash().
make_node() [1/2]
template<typename T> auto coral::make_node () -> NodeObjectPtr inline
Construct a pointer to a NodeObject from a type T.
Definition at line 176 of file coral.h.
References hash().
Referenced by from_json().
make_node() [2/2]
template<typename... Args> auto coral::make_node (Args &&... args) -> NodeObjectPtr inline
Construct a pointer to a NodeObject from the arguments of the constructor.
Definition at line 166 of file coral.h.
register_all_types()
void coral::register_all_types () inline
Definition at line 105 of file register_types.h.
References register_dimensional_types(), and register_non_dimensional_types().
Referenced by main().
register_dimensional_types()
template<int dim, int spacedim> void coral::register_dimensional_types () inline
Definition at line 71 of file register_types.h.
References Utilities::dim_string(), GridGenerator::generate_from_name_and_arguments(), coral::NodeObject::register_function(), coral::NodeObject::register_method(), coral::NodeObject::register_type(), and GridOut::write_vtk().
Referenced by register_all_types().
register_non_dimensional_types()
void coral::register_non_dimensional_types () inline
Definition at line 45 of file register_types.h.
References coral::NodeObject::register_derived_type(), coral::NodeObject::register_elementary_type(), coral::NodeObject::register_type(), and set_type_alias().
Referenced by register_all_types().
set_type_alias()
template<typename T> void coral::set_type_alias (const std::string & alias) inline
Allow callers to override the canonical name used for a given type.
Definition at line 138 of file coral.h.
References coral::detail::type_aliases().
Referenced by register_non_dimensional_types().
to_json() [1/3]
void coral::to_json (json & j, const Connection & conn) inline
Definition at line 534 of file coral_network.h.
References coral::Connection::to_json().
to_json() [2/3]
void coral::to_json (json & j, const Network & net) inline
Definition at line 528 of file coral_network.h.
References coral::Network::to_json().
to_json() [3/3]
void coral::to_json (json & j, const NodeObjectPtr & obj) inline
json serialization of a Nodeobject->
Definition at line 1696 of file coral.h.